# Generated by Django 5.1.5 on 2025-01-31 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/books/')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='essential.book')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz', models.CharField(max_length=255)),
                ('en', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb')], max_length=255)),
                ('definition', models.CharField(max_length=400)),
                ('sentence', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/words/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='essential.unit')),
            ],
        ),
    ]
